---
apiVersion: v1
kind: Service
metadata:
  name: java-tomcat
  labels:
    app: java-tomcat
spec:
  type: NodePort
  selector:
    app: java-tomcat
  ports:
  - protocol: TCP
    port: 3000
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: java-tomcat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-tomcat
    spec:
      containers:
      - name: java-tomcat
        image: marioelias14/java-tomcat-maven-example
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1